name: Manually triggered workflow

on:
  workflow_dispatch:

jobs:
  destroy:
    name: "Terraform destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DB_URL: ${{ secrets.DB_URL }}
          PERM_PASS: ${{ secrets.PERM_PASS }}
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN_RP }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Terraform Init
        run: terraform init

      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
